import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#1a1a1a",
        "on-tertiary-fixed-variant": "#681c73",
        "primary": "#85adff",
        "error-container": "#9f0519",
        "surface-container-low": "#131313",
        "tertiary-container": "#f199f7",
        "secondary-fixed-dim": "#dbb4ff",
        "surface-container-high": "#20201f",
        "primary-dim": "#699cff",
        "tertiary-dim": "#e28ce9",
        "on-error-container": "#ffa8a3",
        "surface-bright": "#2c2c2c",
        "on-secondary-fixed-variant": "#7511c3",
        "inverse-on-surface": "#565555",
        "on-primary-fixed": "#000000",
        "on-primary": "#002c66",
        "outline-variant": "#484847",
        "on-surface-variant": "#adaaaa",
        "secondary": "#c180ff",
        "on-primary-container": "#002150",
        "on-secondary-fixed": "#4f0089",
        "tertiary-fixed-dim": "#e28ce9",
        "background": "#0e0e0e",
        "secondary-dim": "#9c48ea",
        "inverse-primary": "#005bc4",
        "tertiary-fixed": "#f199f7",
        "on-error": "#490006",
        "secondary-fixed": "#e5c6ff",
        "on-background": "#ffffff",
        "secondary-container": "#6f00be",
        "on-tertiary-container": "#5e106a",
        "on-tertiary-fixed": "#3e0047",
        "outline": "#767575",
        "primary-container": "#6e9fff",
        "surface-variant": "#262626",
        "on-tertiary": "#691d74",
        "on-secondary-container": "#e9cdff",
        "surface-container-highest": "#262626",
        "on-primary-fixed-variant": "#002a62",
        "surface-tint": "#85adff",
        "surface-dim": "#0e0e0e",
        "surface": "#0e0e0e",
        "primary-fixed-dim": "#5391ff",
        "on-secondary": "#33005b",
        "error-dim": "#d7383b",
        "primary-fixed": "#6e9fff",
        "error": "#ff716c",
        "tertiary": "#fbabff",
        "surface-container-lowest": "#000000",
        "on-surface": "#ffffff",
        "inverse-surface": "#fcf9f8",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
        serif: ["'Playfair Display'", "'Lora'", "'Merriweather'", "'Crimson Pro'", "'Source Serif 4'", "serif"],
        mono: ["'JetBrains Mono'", "'Fira Code'", "ui-monospace", "monospace"],
      },
      borderRadius: {
        none: "0",
        DEFAULT: "0.375rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      animation: {
        "fade-in-up": "fadeInUp 0.8s ease-out forwards",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "explode-in": "explodeIn 0.7s cubic-bezier(0.16, 1, 0.3, 1) both",
        "stagger-fade": "staggerFadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) both",
        "scale-reveal": "scaleReveal 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.15s both",
        "slide-left": "slideInLeft 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.1s both",
        "slide-right": "slideInRight 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.1s both",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        explodeIn: {
          "0%": { opacity: "0", transform: "scale(0.92) translateY(24px)", filter: "blur(8px)" },
          "60%": { opacity: "1", transform: "scale(1.02) translateY(-4px)", filter: "blur(0)" },
          "100%": { opacity: "1", transform: "scale(1) translateY(0)", filter: "blur(0)" },
        },
        staggerFadeUp: {
          "0%": { opacity: "0", transform: "translateY(32px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleReveal: {
          "0%": { opacity: "0", transform: "scale(0.85)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;